### ISSUE TITLE
Broken syntax highlighting

### ISSUE THREAD

**Issue by alem0lars** [HerringtonDarkholme/yats.vim#31] opened 2018-01-16 08:36 UTC
![2018-01-16-093603_1044x1362_scrot](https://user-images.githubusercontent.com/336957/34979112-b49172f4-faa0-11e7-81c3-d150a4986b92.png)

**Comment by alem0lars** [comment] 2018-01-16 08:48
More examples:

![2018-01-16-094801_1137x1003_scrot](https://user-images.githubusercontent.com/336957/34979706-62d2792a-faa2-11e7-95b5-d0fb9a0f2568.png)

**Comment by HerringtonDarkholme** [comment] 2018-01-16 08:57
Duplicate of #5

**Comment by alem0lars** [comment] 2018-01-16 08:58
I've updated to the latest github version and I'm still getting syntax error!

**Closed by HerringtonDarkholme** 2018-01-16 08:57 UTC

**Comment by HerringtonDarkholme** [comment] 2018-01-16 09:03
It is closed because this issue is duplicate, not fixed.
