### ISSUE TITLE
Syntax highliting

### ISSUE THREAD

**Issue by phaalonso** [HerringtonDarkholme/yats.vim#193] opened 2020-06-19 20:37 UTC
(Sorry for my english)

Hi, I am new to neovim and I'm trying to use yats and noticied that some keywords aren't being colored like instanceof, class names like in this image 
![image](https://user-images.githubusercontent.com/26033899/85177899-7d27a000-b253-11ea-9bbc-c01a2cdbaec8.png)

**Comment by tapsu01** [comment] 2020-10-18 16:48
I also have the same problem

**Comment by tommyc38** [comment] 2020-11-13 17:44
@phaalonso @tapsu01 , The issue you are having is caused by your theme.  Most Vim themes use the default vim typescript highligh groups.  To take advantage of yats, you need to add in the highlight groups that yatz created.  For example, I use the darcula theme (https://github.com/doums/darcula).  I changed the Typescript section to this:

```
" Typescript
hi! link typescriptImport Keyword
hi! link typescriptExport Keyword
hi! link typeScriptCastKeyword Keyword
hi! link typeScriptCastObjectLiteral Keyword
hi! link typeScriptDecorator PreProc
hi! link typeScriptTemplateSB Normal
hi! link typeScriptArrowFuncDef Function
hi! link typeScriptArrowFuncArg Normal
hi! link typeScriptArrowFunc Normal
hi! link typescriptVariableDeclaration Normal
hi! link typeScriptFuncName Function
hi! link typeScriptFuncCallArg Normal
hi! link typescriptDocNotation typescriptDocTags
hi! link typescriptDocNamedParamType typescriptDocComment
hi! link typescriptDocParamType typescriptDocComment
hi! link typescriptBOMNavigatorProp Function
hi! link typeScriptConstructor Keyword
hi! link typeScriptDestructureVariable Normal
hi! link typeScriptComputeMember Function
hi! link typeScriptProp Normal
hi! link typescriptNull Keyword
hi! link typescriptInterfaceName Normal
hi! link typescriptUnion Normal
" wont differientiate between prop and member because it's too expensive see https://github.com/HerringtonDarkholme/yats.vim/issues/93 
" hi! link typescriptMember typescriptLabel
hi! link typescriptPaymentShippingOptionProp Normal
hi! link typeScriptDOMFormProp typescriptLabel
hi! link typeScriptBOMWindowProp Normal
call s:Hi('typescriptLabel', s:p.cStructField, s:p.null,'')
hi! link typeScriptCall Normal
hi! link typeScriptPreProc typescriptLabel
hi! link typeScriptFunctionCall Function
hi! link typescriptObjectLiteral Normal
hi! link typescriptObjectMethod Function
hi! link typeScriptObjectLabel typescriptLabel
hi! link typeScriptFunction Function
hi! link typeScriptOptionalMark Normal
call s:Hi('typescriptBoolean', s:p.keyword, s:p.null,'')
hi! link typeScriptReserved Keyword
hi! link typeScriptVariable Keyword
hi! link typeScriptIdentifier Keyword
hi! link typescriptBraces NormalFg
hi! link typescriptDocComment docComment
hi! link typescriptDocParam docComment
hi! link typescriptParens NormalFg
hi! link typescriptOpSymbols Constant
hi! link typescriptRegexpString Number
hi! link typescriptSpecial Keyword
hi! link typescriptLogicSymbols Constant
hi! link typescriptExceptions Keyword
call s:Hi('typescriptDocTags', s:p.docComment, s:p.null, 'bold,italic,underline')
call s:Hi('typescriptGlobalObjects', s:p.tsObject)
```

Now I have all of the highlighting exactly the way I want it.  Moreover, I even changed a few of the colors in the palette to my liking and have since moved the theme to my own custom plugin so Plug won't update it and remove all the change's I have made.  As a tip, any plugin you use has a syntax directory.  This is where all of the highlight groups are defined which you can add to your theme file and specify colors you want to change to the plugin using your palette...I use this approach for NERDTree and Vista.  Lastly, you need to use https://github.com/gerw/vim-HiLinkTrace/blob/master/plugin/hilinks.vim as it will really help you figure out which group is highlighting the word under the cursor.  Once you figure this out, you will easily be able to change all the colors to your liking, for any plugin, easily.  Hopefully this helps.


Here is a screenshot:
![image](https://user-images.githubusercontent.com/10190567/99103564-017d1580-259d-11eb-8f2d-dec7e0a5808b.png)

**Comment by phaalonso** [comment] 2020-11-13 18:29
Thanks ♥️

**Comment by tapsu01** [comment] 2020-11-14 08:59
@tommyc38 thank you. I tried it but nothing working. My [init.vim](https://github.com/tapsu01/dotfiles/blob/master/init.vim)

**Comment by tommyc38** [comment] 2020-11-14 14:42
@tapsu01 You are using Dracula when you should be using Darcula, see link above.

**Comment by HerringtonDarkholme** [comment] 2020-11-16 05:24
Thank @tommyc38 for answering the question! I think the problem should be solved in color theme not in the syntax repo. So closing now.

**Closed by HerringtonDarkholme** 2020-11-16 05:24 UTC
