### ISSUE TITLE
Calling a function with specified generic in an object method breaks the syntax

### ISSUE THREAD

**Issue by chadrien** [HerringtonDarkholme/yats.vim#30] opened 2018-01-15 12:17 UTC
![bork](https://user-images.githubusercontent.com/1788218/34942004-b39fed28-f9fe-11e7-9440-42aa6e3c2914.gif)

When the line is uncommented, `const` hi is `typescriptReserved`, when commented it's `typescriptEnumKeyword` (which I guess is the expected one)

**Comment by HerringtonDarkholme** [comment] 2018-01-15 12:20
Probably it won't be supported.

Dot property access is contained syntax highlight. If we relax it to be a global syntax, it might break a lot of other highlighting.

**Comment by chadrien** [comment] 2018-01-15 12:26
Is there a way then to make it the other way around, and "lose" the `typescriptTypeReference` syntax in this case instead? I.e. you'd still be able to right valid TS code, without breaking the rest of the syntax highlight, simply in this case the types wouldn't be highlighted.

Imho the loss of a tiny portion of syntax highlight is worth if it means being able to write valid TS code with better typing.

But I could understand if it's not possible at all, I'm no vim syntax expert sadly 😅

**Comment by HerringtonDarkholme** [comment] 2018-01-15 12:30
Sorry, my fault.

I mistaken this issue is supporting dot access highlighting after dot.

generic function error should be fixed.

**Comment by chadrien** [comment] 2018-01-15 12:32
No worries, tbh it was not simple to describe what was wrong here, so I also take the blame of not explaining the problem well enough :)

**Comment by HerringtonDarkholme** [comment] 2018-01-15 12:47
I'm sorry but the real issue here is generic syntax is intractable in Vim syntax.

For example, `foo<number>(a)` is valid javascript syntax, a chained comparison. But TypeScript compiler also got this wrong.

https://www.typescriptlang.org/play/#src=var%20foo%20%3D%203%0Avar%20number%20%3D%204%0Avar%20a%20%3D%204%0A%0Afoo%3Cnumber%3E(a)

The parenthesis aren't matched due to this ambiguity. Thus this error.

**Comment by chadrien** [comment] 2018-01-15 13:08
I'm sorry, maybe there's something I didn't understood, but

```
var foo = 3
foo<number>(4)
```

Not working is absolutely normal since it's invalid code. A correct example would be

```
var foo = function<T>(t: T):T { return t; }
foo<number>(4)
```

Did I miss something?

**Comment by HerringtonDarkholme** [comment] 2018-01-15 13:27
For `foo<number>(a)`, yats thinks it is a comparison, not a function call.

The problem is that we cannot tell if `<` is a generic bracket or a comparison operator. Vim's syntax approach cannot do back tracking.

**Comment by chadrien** [comment] 2018-01-15 14:47
Ah yes, I see what you mean. Well 💩

Thanks for looking into this!

**Comment by HerringtonDarkholme** [comment] 2018-02-05 15:15
I fixed it in master! Cheers!

**Closed** 2018-02-05 15:15 UTC
Labels: bug, wontfix
