### ISSUE TITLE
Comments aren't highlighted in class methods

### ISSUE THREAD

**Issue by Sammyalhashe** [HerringtonDarkholme/yats.vim#100] opened 2019-03-06 18:30 UTC
Maybe I've done something wrong, but I've noticed that comment highlighting in class methods are not highlighted properly. Comments are correctly highlighted outside of class methods though. See the below image as an example.

<img width="621" alt="screen shot 2019-03-06 at 1 27 54 pm" src="https://user-images.githubusercontent.com/20797997/53904337-cda1cc80-4013-11e9-9c8c-3f2014832c02.png">

**Comment by HerringtonDarkholme** [comment] 2019-03-07 02:03
Can you paste the code? I cannot reproduce it and the `const` keyword isn't highlighted correctly in your screenshot.

I guess somewhere else went wrong.

**Comment by Sammyalhashe** [comment] 2019-03-07 03:04
```typescript
import { Injectable } from '@angular/core';
import { HttpRequest, HttpResponse } from '@angular/common/http';

const maxAge = 30000;
@Injectable()
export class RequestCache {
    // cache
    cache = new Map();

    /*
     * Intercepts the request and checks if the data, keyed by the url
     * is already in the cache. If it is, it returns the stored response
     */
    get(req: HttpRequest<any>): HttpResponse<any> | undefined {
        const url = req.urlWithParams;

        // see if it is already in the cache
        const cached = this.cache.get(url);

        if (!cached) {
            return undefined;
        }

        /*
        if (this.cache.has('total')) {
            cached = this.cache.get('total');
        }
        */

        const isExpired = cached.lastRead < Date.now() - maxAge;
        const expired = isExpired ? 'expired ' : '';
        return cached.response;
    }

    /*
     * On the condition that the get method returns undefined, the
     * interceptor will download the data, then send it to this method.
     * The resulting response will then be stored in the cache.
     */
    put(req: HttpRequest<any>, response: HttpResponse<any>): void {
        const url = req.url;
        const entry = { url, response, lastRead: Date.now() };
        this.cache.set(url, entry);

        // this is a comment
        /*
        if (this.cache.has('total')) {
            const temp = this.cache
                .get('total')
                .response.body.trips.concat(entry.response.body.trips);
            entry.response.body.trips = temp;
            this.cache.set('total', entry);
        } else {
            this.cache.set('total', entry);
        }
        */

        // delete any expired entries
        const expired = Date.now() - maxAge;
        this.cache.forEach(expiredEntry => {
            if (expiredEntry.lastRead < expired) {
                this.cache.delete(expiredEntry.url);
            }
        });
    }
}
```

**Comment by HerringtonDarkholme** [comment] 2019-03-07 03:12
I didn't see highlight mismatching myself. I think it might be syntax highlight delay (which can be fixed by scrolling vim around)

![image](https://user-images.githubusercontent.com/2883231/53929759-bde4bf80-40c9-11e9-878c-92bb6f0b4909.png)

**Comment by Sammyalhashe** [comment] 2019-03-07 03:16
Hmm. Like scrolling around with the mouse or with your standard hjkl? Because either don't seem to fix it.

**Comment by HerringtonDarkholme** [comment] 2019-03-07 03:33
Can you disable all other plugins and use a minimal vimrc?

**Comment by Sammyalhashe** [comment] 2019-03-07 19:05
Sorry for the late reply, will try soon

**Comment by Sammyalhashe** [comment] 2019-03-07 19:15
Yeah, it seems to be another plugin interfering. Hard to say which one it is haha.
<img width="781" alt="screen shot 2019-03-07 at 2 10 25 pm" src="https://user-images.githubusercontent.com/20797997/53982602-4e7bc980-40e3-11e9-97ab-6a09c8f1b6e6.png">

**Closed** 2019-03-08 03:23 UTC

**Comment by jtbairdsr** [comment] 2019-03-14 18:26
for what it is worth, the `maxmellon/vim-jsx-pretty` plugin is what broke it for me... Hope this helps someone else.
